# Generated by Django 2.1.4 on 2018-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodinfo',
            name='istop',
            field=models.BooleanField(default=True),
        ),
    ]
